version: "3.9"
services:
  web:
    container_name: satcm
    build: .
    command: rake db:migrate
    command: rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/satcm
    ports:
      - "3000:3000"
